### ISSUE TITLE
Could you please provide the code for ablation study with LLaMA-VID

### ISSUE THREAD

**Issue by YuchenLiu98** [Yxxxb/VoCo-LLaMA#14]
Thanks the authors for amazing job and released code. I wonder could you please provide the code for ablation study with LLaMA-VID in Table 3

**Comment by Yxxxb** [comment]
Thanks for your interest!

The experimental setup in Table 3 is to replace the encoder with EVA-G and train with exactly the same setup as LLaMA-VID, as you can achieve by modifying the build encoder. We will provide the relevant code later.
