### ISSUE TITLE
Final Weights

### ISSUE THREAD

**Issue by Andrew-Zhang** [Yxxxb/VoCo-LLaMA#2]
Great Idea! I was wondering if the final model weights would be provided. Also, how long did training take?

**Comment by Yxxxb** [comment]
Hi,

Thank you for your interest in our work! We'll have the final model weights available soon.
On 8*A100 (40G), the model takes about 7 hours per epoch (2 epochs in total) to train. The main training time is almost identical to that of LLaVA's supervised fine-tune stage.

**Comment by Andrew-Zhang** [comment]
Thanks!
