### ISSUE TITLE
Missing setup.py or pyproject.toml

### ISSUE THREAD

**Issue by Andrew-Zhang** [Yxxxb/VoCo-LLaMA#3]
I get the following error when I follow the installation instructions:

```
$ pip install -e .

Obtaining file:///projects/vision/azhang42/experiments/VoCo-LLaMA
ERROR: file:///projects/vision/azhang42/experiments/VoCo-LLaMA does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```

Does this project have the same requirements as llava?

**Comment by Yxxxb** [comment]
Hi,

Thanks for the suggestion, I've added a pyproject.toml within the repository and the dependencies we're using are exactly the same as LLaVA.

**Comment by Andrew-Zhang** [comment]
Thanks!
