### ISSUE TITLE
Hyperparameters for different number of voco tokens

### ISSUE THREAD

**Issue by Andrew-Zhang** [Yxxxb/VoCo-LLaMA#5]
Hello! I am looking to train the model on 1 VoCo token. Therefore, I set `voco_num` to 1 in llava_arch.py and the number of inserted voco tokens to 1 in train_compress.py. I was wondering if I should use the same hyperparamters that were used to train with the default of 2 voco tokens. Thanks for any help in advance.

**Comment by Yxxxb** [comment]
Hi Andrew,

We are very sorry that we didn't set a hyperparameter for the number of VoCo tokens during the code cleanup, we will add it later. The changes you made are correct, change the number of VoCo tokens in the following two places:
https://github.com/Yxxxb/VoCo-LLaMA/blob/main/llava/train/train_compress.py#L443
https://github.com/Yxxxb/VoCo-LLaMA/blob/main/llava/model/llava_arch.py#L236
Besides, for fair comparisons, we used the exact same hyperparameters when we changed the number of VoCo tokens.

**Comment by Andrew-Zhang** [comment]
Ok thanks!
