### ISSUE TITLE
VoCo-LLaMA checkpoints

### ISSUE THREAD

**Issue by pastapeter** [Yxxxb/VoCo-LLaMA#6]
Hello, Thank you for your work! I think it has a great novelty.

I have some questions about checkpoint! 
Are there no checkpoints for VoCo-LLaMA?
I only have 1 GPU(L40), and just want to check inference or evaluation. But I cannot find voco-llama checkpoints in this repository.

if there is plan to upload the checkpoints, when would you upload them?

Thank you

**Comment by Yxxxb** [comment]
Hi,

Thank you for your interest in our work! We'll have the final model weights available soon.
We're in the process of cleaning the inference code. We'll be open sourcing the relevant checkpoints soon after this is done.

Best Regards.
