### ISSUE TITLE
How to compare the inference time?

### ISSUE THREAD

**Issue by Gumpest** [Yxxxb/VoCo-LLaMA#8]
Hi, authors. I wonder how to present the efficiency via inference time.

**Comment by Gumpest** [comment]
Besides, I want to learn how to compute the CUDA time. Thanks a lot.

**Comment by Yxxxb** [comment]
Hi,

[llama.cpp](https://github.com/ggerganov/llama.cpp), [LLaVA-cli](https://github.com/haotian-liu/LLaVA?tab=readme-ov-file#cli-inference) or simple time function of Python can complete the measurement of time.

**Comment by Gumpest** [comment]
@Yxxxb What batch size do you use?

**Comment by Yxxxb** [comment]
The overall batch size is 128, which is the same as LLaVA SFT stage. You could check the training Hyperparameters in the "Additional Implement Details" section of our paper's appendix.
